### PR TITLE
Allow accessing compilation object in generate() callback

### PR DESCRIPTION
**Pull request by t-moennich**
This PR contains:

- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking.

List any relevant issue numbers:

### Description

This PR adds access to the [Compilation](https://github.com/webpack/webpack/blob/master/lib/Compilation.js) object in the `generate()` callback to allow working with the new `ChunkGraph` API

### CODE REVIEW

**Comment by shellscape** [comment]
Thanks for opening a PR. Looks like a good change to me. As the PR mentions, we don't accept fixes or features without accompanying tests. You'll likely have to update the test for `generate`, and I'd like to see a test added for that new parameter specifically.

**Comment by shellscape** [comment]
@t-moennich a quick ping. If there's no action on this PR for another 14 days I'll have to assume it's been abandoned.

**Comment by shellscape** [comment]
Closing as abandoned

**Comment by simeyla** [comment]
@shellscape I thought this was exactly what I was looking for but it was never merged. Is there a workaround for this issue.

I've been getting errors like this when using `generate` to try to access deprecated methods such as `file.chunk.getModules()`

> There was no ChunkGraph assigned to the Chunk for backward-compat (Use the new API)

 Is there another way to access `ChunkGraph` inside `Generate` or to actually force the legacy ChunkGraph to be assigned to each file inside `generate` ?

**Pull request closed without merging**
