### PR TITLE
feat: expand allowed removeKeyHash length from exactly 32 to 16-32

### PR DESCRIPTION
**Pull request by cascornelissen**
This PR contains:

- [ ] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [x] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking.

List any relevant issue numbers:

### Description
As discussed in https://github.com/shellscape/webpack-manifest-plugin/issues/241.

### CODE REVIEW

**Comment by shellscape** [comment]
Change looks good, but we'll need a test added to approve it.

**Comment by cascornelissen** [comment]
Cool, I've added a test, don't have any experience with ava so let me know if something should be changed ✌🏼

**Comment by shellscape** [comment]
Click on the `Details` link on the failing check, and it'll take you to: https://github.com/shellscape/webpack-manifest-plugin/pull/248/checks?check_run_id=1844379311. Looks like your test on Windows is returning an unexpected value.

**Comment by cascornelissen** [comment]
I got that part but it's failing on the existing test (which I haven't touched), not on the test I've added, unless I'm misinterpreting the output?

**Comment by cascornelissen** [comment]
Ping @shellscape, sorry to bother you but I wanted to make clear that I need your help to finish this up 😅

**Comment by shellscape** [comment]
So the way the output reads, the test for the `removeKeyHash` is failing on windows. That's an option that you did modify, even if you didn't touch the tests for it. This is part of why we have unit tests like this in place - it catches regressions in seemingly innocent changes to parts of the code. Since you changed how the option works, you'll have to check that test on Windows (probably through console.log and looking at test results here) and see how/why your changes modified what that test expected.

**Comment by cascornelissen** [comment]
Apparently the test output was incorrect, deleting it and letting it regenerate solved the problem. Couldn't test it locally so had to use the GH action a bunch of times.

**Comment by shellscape** [comment]
bueno! 
thanks!

**Pull request merged**
